AllCops:
  Exclude:
    - db/schema.rb

Rails/ActionFilter:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes
